services:
  fluentbit:
    image: fluent/fluent-bit:4.0
    container_name: fluentbit
    restart: on-failure
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./scripts/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./scripts/fluent-bit/map.json:/fluent-bit/etc/map.json
      - ./logs:/app/logs
    networks:
      - app_net
    depends_on:
      - loki
  
  loki:
    image: grafana/loki:3.5.7
    container_name: loki
    restart: on-failure
    command: -config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./scripts/loki:/etc/loki
    networks:
      - app_net

  grafana:
    image: grafana/grafana:12.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    networks:
      - app_net
    depends_on:
      - loki

volumes:
  grafana_data:

networks:
  app_net:
    driver: bridge